name: Baixando Lista
on:
  schedule:
    - cron: '*/30 * * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Tentando
      run: |
        wget https://github.com/guiworldtv2/plugin.video.cbsnetwork/archive/refs/heads/dev.zip -O /tmp/plugin.video.cbsnetwork.zip
        unzip -o /tmp/plugin.video.cbsnetwork.zip -d /tmp/
        cd /tmp/plugin.video.cbsnetwork-dev
        zip -r /github/workspace/$ZIP_FILE .
    - name: Add, commit, and push changes
      run: |
        git add -A
        git commit -m "Download and zip repository"
        git push
