name: Download do arquivo plugin.video.cbsnetwork.zip

on:
  schedule:
    - cron: "0 0 * * 0" # Executa a cada domingo às 00:00

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Excluir arquivo zip existente
      run: rm -f plugin.video.cbsnetwork.zip
    - name: Baixar novo arquivo zip
      run: curl -o plugin.video.cbsnetwork.zip https://github.com/guiworldtv2/plugin.video.cbsnetwork/archive/refs/heads/dev.zip

    - name: commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
          
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date '+%Y-%m-%d')"
        
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  
