# This is a basic workflow to help you get started with Actions

name: Separados

# Controls when the action will run. 
on:
  schedule:
    - cron: "4 * * * *"
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runner's shell
      #- name: Run a one-line script
      #  run: echo testing!
          
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Excluir arquivo zip existente
        run: rm -f plugin.video.cbsnetwork.zip
      - name: Baixar novo arquivo zip
        run: curl -o plugin.video.cbsnetwork.zip https://github.com/guiworldtv2/plugin.video.cbsnetwork/archive/refs/heads/dev.zip           
        
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%Y-%m-%d')"
        
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
